export { default as Home } from './Home'
export { default as InternalServerError } from './InternalServerError'
export { default as Login } from './Login'
export { default as NotFound } from './NotFound'
export { default as Profile } from './Profile'
export { default as Register } from './Register'
